"""Check the actual schema generated by LangChain for create_long_term_memory."""

import asyncio
import json

from agent_memory_client import MemoryAPIClient, MemoryClientConfig
from agent_memory_client.integrations.langchain import get_memory_tools


async def main():
    # Initialize memory client without health check
    config = MemoryClientConfig(base_url="http://localhost:8000")
    memory_client = MemoryAPIClient(config)

    # Get memory tools
    tools = get_memory_tools(
        memory_client=memory_client,
        session_id="test_session",
        user_id="alice",
        tools=["create_long_term_memory", "add_memory_to_working_memory"],
    )

    # Check both tools
    for tool in tools:
        print("=" * 80)
        print("Tool Name:", tool.name)
        print("\nTool Description:")
        print(tool.description)
        print("\nTool Args Schema:")
        print(json.dumps(tool.args_schema.schema(), indent=2))
        print()


if __name__ == "__main__":
    asyncio.run(main())
